name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Check formatting
      run: dotnet fantomas . -r --check
    - name: Restore dependencies
      run: dotnet restore ./FCSBenchmark.sln
    - name: Build
      run: dotnet build --no-restore ./FCSBenchmark.sln
